# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'wordgrid2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wordgrid2

  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Firestore', '~> 5.3.0'
  pod 'Firebase/Auth', '~> 5.3.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
